### ISSUE TITLE
High cpu usage while SageTV is idle

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#113]
The SageTV process uses 30% cpu while idle. If I execute the following command, SageTV idle cpu usage drops to 0-1%.

sage_MiniClientSageRenderer_stopUIServer()

I created a plugin that executes that command during SageTV startup, but is there a more permanent fix?

**Comment by Narflex** [comment]
I looked into this issue for him awhile back (which is where he got the
idea to do that command for fixing it).  I have no idea why this is a
problem....all that code is doing is select() on a socket; but for some
reason after a certain amount of time it starts using a bunch of CPU.  The
only way I could see investigating this further is if another dev is able
to reproduce the problem and then analyze it more deeply....but I haven't
heard of anybody else hitting this issue.

On Fri, Mar 25, 2016 at 2:33 AM, 49studebaker <notifications@github.com>
wrote:

> The SageTV process uses 30% cpu while idle. If I execute the following
> command, SageTV idle cpu usage drops to 0-1%.
>
> sage_MiniClientSageRenderer_stopUIServer()
>
> I created a plugin that executes that command during SageTV startup, but
> is there a more permanent fix?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/113>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by roymcd** [comment]
Not sure if this is relevant, but I had a problem a few years ago with high cpu use under linux due to to IR remote polling by the dvb_usb driver.  Turned it off in /etc/modprobe.conf or /etc/modprobe.d/local.conf with the following entry.  Although I believe current dvb_usb modules have RC polling turned off by default.

# disable remote control polling for usb dvb sticks
# which is causing high cpu load
options dvb_usb disable_rc_polling=1

**Comment by Narflex** [comment]
He's using Windows. But thanks for the tip for others. :-)

Jeff Kardatzke

**Comment by Narflex** [comment]
Stale issue, no other users have reported this problem, closing.
