### ISSUE TITLE
SageTV is preventing my htpc from entering sleep.

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#124]
SageTV is preventing my htpc from entering sleep.

[sagetv_0.zip](https://github.com/google/sagetv/files/200728/sagetv_0.zip)

**Comment by Narflex** [comment]
SageTV did let the computer go to sleep in that log file; it happened right here:

Fri 4/1 22:30:40.781 [main@192e0f4] System power is suspending

The computer then woke up again a few minutes later here:

Fri 4/1 22:33:03.155 [main@192e0f4] SageTV pausing on wakeup to let drivers load properly...

in order to complete this scheduled recording at 22:35:

Fri 4/1 21:29:57.315 [Scheduler@56e5bc] MUST SEE FINAL-AVerMedia M780 PCIe Audio/Video Capture 1-[A[829790,829679,"The Late Show With Stephen Colbert",19628@0401.22:35,62,T]
