### ISSUE TITLE
More specific/accurate EPG server failure error

### ISSUE THREAD

**Issue by SageWizdom** [google/sagetv#134]
Per an interesting post on the forum (http://forums.sagetv.com/forums/showthread.php?t=63173)

I would propose a bug/feature change that when the sever tries to reach out to the EPG server the error should be more specific.  In this instance, a user had a valid key, but their home firewall was blocking the EPG port (not the computer).  The computer thought it was configured correctly (all ports available) and the user only realized this once they contacted Narflex and found out that their keys were valid.   

In this case troubleshooting might have been easier if there were specifically different errors for...

"The EPG server could not be reached, check that port XYZ is not blocked" versus
"The EPG server credentials are invalid, confirm your sage license key is approved" or "Connection to EPG failed due to an invalid key"

Or something similar

**Comment by Narflex** [comment]
Great idea. :)  I'll do it sometime in the near future if somebody else doesn't beat me to it...or if anybody else wants guidance on how to do it; it's a great way to learn more about the code. :)

**Comment by Narflex** [comment]
I did notice in the code that SageTV does log one of these two messages if the client doesn't have an EPG license key and it's trying to contact the server. 

You do not have a SageTV license, you cannot download EPG data.

OR

You do not have a SageTV license or an EPG plugin installed, you cannot download EPG data.

The main problem with this (and I have no workaround) is that if you're using an invalid or improperly formatted license key...then you'll just get disconnected from the server (and the server doesn't tell you anything about that).

Do you know if most of the problems have been due to just no license key being there at all...or due to it being badly formatted/incorrect?

**Comment by SageWizdom** [comment]
I do not know.  I was imagining a couple of scenarios.  

1) New install and user does not have/forgets to configure a key
2) User enters the key incorrectly or enters an invalid key
3) SageTV Server can not reach the EPG server

I think that is all of them.

**Comment by CraziFuzzy** [comment]
Really, the server needs to respond with some sort of error if the key is invalid - just disconnecting is causing the ambiguity.  Without this change at the EPG server's end, there may not be much that can be done on our end.

1.) Lack of a key should be recognized in Sage prior to even attempting to connect - this would be an STV change in the EPG setup screens.
2.) Incorrect key needs to be reported by the server back to Sage, so it can be reported as such.
3.) No response from the server should state the current error that it couldn't be reached.

**Comment by SageWizdom** [comment]
That seems like the right logic to apply.

**Comment by Narflex** [comment]
I've now updated the EPG server so that it'll return an INVALIDKEY message after submitting an invalid license key, rather than just returning OK and then disconnecting. I'll be doing the client side changes soon to recognize that so this'll be more helpful to users.
