### ISSUE TITLE
Inconsistency in file paths returned in APIs

### ISSUE THREAD

**Issue by JREkiwi** [google/sagetv#140]
### Using a windows client connected to a Linux server

Playback shows file playing is /var/media/myvideo.mpg

GetFileForSegment() returns \var\media\myvideo.mpg

IsFilePath(GetFileForSegment()) returns false

IsFilePath("/var/media/myvideo.mpg") returns true

### Using a Windows client connected to a Windows server

Playback shows file playing is d:\media\myvideo.mpg

GetFileForSegment() returns d:\media\myvideo.mpg

IsFilePath(GetFileForSegment()) returns true

IsFilePath("d:/media/myvideo.mpg") returns true

**Comment by Narflex** [comment]
Do you have interest in debugging this yourself? :)  I'm not sure why it isn't working...from looking at the code it should be.

IsFilePath is a server based API call...so it's executed there (which is why it works fine on Windows).

The GetFileForSegment call returns a java.io.File object and is executed locally. That's why on Windows it shows the '\' char instead of the '/' char (that's expected behavior). In the client/server protocol, there's methods in SageTVConnection called read/writeObjectFromStream which convert between the wire protocol and Java objects. So when the Windows client sends the arg for the IsFilePath call as a File object, it will get tagged as a MINOR_FILE type object and sent as a String and then on the server side it should be calling IOUtils.convertPlatformPathChars  on the String to fix the / vs \ issue, which will then causedthe File object the server constructs to be correct...however, it must not be because IsFilePath is not returning the proper value.

Alternatively...there could be a mistake in the code you had that proved this, so it's worth double-checking on your end first as well (since I don't see a clear bug in the SageTV code and I definitely did something at some point to deal with this case).

**Comment by JREkiwi** [comment]
Debugging this is way out of my league, but your explanation shows I need to be more specific in my specific test case.

With Windows client on Linux server

Playback shows file playing is /var/media/myvideo.mpg

`cspmediafile = GetFileForSegment(Airing, 0)`

> cspmediafile = \var\media\myvideo.mpg

`cspmediafile = (java_lang_String_replaceFirst(("" + cspmediafile), "\\.\\w+$", ".edl"))`

> cspmediafile = \var\media\myvideo.edl

`IsFilePath(cspmediafile)`

> false

`cspmediafile = java_lang_String_replaceAll(new_java_lang_String(cspmediafile), "\\\\", "/")`

> cspmediafile = /var/media/myvideo.edl

`IsFilePath(cspmediafile)`

> true

**Comment by Narflex** [comment]
I'm confused now...is this an issue with the API, or was it just something
in your own code that was wrong? (Since what you post now is referring to
EDL files)

Jeff Kardatzke
Sent from my Android

**Comment by JREkiwi** [comment]
I believe it's an API problem.  From your description above it looks like the IsFilePath() DeleteFilePath() APIs are not performing the IOUtils.convertPlatformPathChars process on Linux servers, but do on Windows servers.

I was showing my code, just in case what I'm doing falls outside the normal use case for IsFilePath().  I'm testing to see if a matching EDL file exists for a Video file.

**Comment by Narflex** [comment]
The conversion will only happen if a java.io.File object is passed in. It
will not do it for String. Does that explain it then?

Jeff Kardatzke

**Comment by JREkiwi** [comment]
It does.

Thanks for your time looking at this
