### ISSUE TITLE
Another UI Hang

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#158]
[SageTV UI Hang.zip](https://github.com/google/sagetv/files/381142/SageTV.UI.Hang.zip)

**Comment by Narflex** [comment]
This looks like it's being caused by a plugin that's making bad invocations of a method:

Thu 7/14 19:48:58.519 [ActiveRender-SAGETV_PROCESS_LOCAL_UI@139f539] sage.jep.ParseException: UNKNOWN METHOD ERROR name=java_io_RandomAccessFile_readFully args=[java.io.RandomAccessFile@1bb3375, 252.25	390.61	]

**Comment by JREkiwi** [comment]
Yes,  it's the same as the problem in [this](https://github.com/google/sagetv/issues/157) issue.  He's using an old version of the Comskip Playback plugin

John
