### ISSUE TITLE
UI Hangs

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#163]
[sagetv_0.txt](https://github.com/google/sagetv/files/417640/sagetv_0.txt)

**Comment by 49studebaker** [comment]
[Crash while accessing OSD menu.zip](https://github.com/google/sagetv/files/484202/Crash.while.accessing.OSD.menu.zip)
[Java error 1.zip](https://github.com/google/sagetv/files/484203/Java.error.1.zip)

**Comment by Narflex** [comment]
I looked at the hs_err_pid files you had there and a couple of them were very weird random crashes, likely due to some kind of memory corruption. Another one was a crash that could be similar, but was during intitalization of the Direct3D rendering engine. You may want to do a memory test on your system (I would if I saw these crashes)...but usually that's not the problem. I can't even be sure the problem is related to SageTV at all based on the crash stack traces.

**Comment by 49studebaker** [comment]
I ran the Windows Memory Diagnostic tool and it did not find any memory errors.

**Comment by Narflex** [comment]
Stale issue, closing.
