### ISSUE TITLE
SD Plugin is pulling Spanish language series information sometimes

### ISSUE THREAD

**Issue by Narflex** [google/sagetv#267]
@enternoescape I just noticed this in my setup where the Series Information for Pawn Stars is in Spanish (and it's coming that way from Airings on English channels).  First time I've seen this problem. It's using the SD source and the latest build from GitHub.

**Comment by enternoescape** [comment]
It always tries to use English if it's available or another preferred language if desired for programs. The series description info that's imported doesn't have a language associated with it, so if it's Spanish, it's more than likely a problem on the Schedules Direct side. If you want to see exactly what's coming in you can stop SageTV, set debug_sd=false to true, delete sdmd5prog and sdmd5sched, start SageTV and trigger an EPG update. You will then have a file named sd_epg.log that you can see exactly what is being returned by Schedules Direct. Deleting those files will cause everything to be updated. You can be more surgical by removing the external ID's of interest from sdmd5prog and deleting sdmd5sched so that the actual airings will be reimported.

**Comment by enternoescape** [comment]
...re-importing the airings will trigger the shows to be updated because it will see that we don't have a hash for them which means we need to update/add them.

**Comment by enternoescape** [comment]
After looking at the code involved, I do see one possible entry point for this to happen. If the series description doesn't return anything and we pull our description from an SH pre-pended episode airing on a non-English channel that does not have an English description, you could get a non-English series description. This situation is very unlikely, but we can fix it if this is in fact what happened by just forcing English (or the preferred digraph) and if we don't have an English description.

**Comment by enternoescape** [comment]
I saw this in my log, so I'm really leaning towards SD had a problem that they just fixed:
```
POST https://json.schedulesdirect.org/20141201/metadata/description (send): 
["EP011594940001"]
https://json.schedulesdirect.org/20141201/metadata/description (received): 
{"SH011594940000":{"code":0,"description100":"Three generations of men run a family-owned pawn shop in Las Vegas.","description1000":"This series opens the doors to the only family-run pawnshop in Las Vegas, where three generations of the Harrison family use their sharp-eyed skills to assess what's real and what's fake. Objects the colorful customers bring in range from the obscure to the truly historic, and it's up to the guys at the Gold & Silver Pawn Shop -- with help at times from their network of experts -- to reveal the sometimes surprising answer to \"What's this worth?\""}}
```

**Comment by Narflex** [comment]
Alright, I erased those files and am letting it run an update so I'll see what happens when it's done. :)

**Comment by Narflex** [comment]
All good now, back to English and has the artwork again. :)
