### ISSUE TITLE
Problems with OTA HDHomerun Scan

### ISSUE THREAD

**Issue by texneus** [google/sagetv#338]
I am having an issue getting a channel scan to function correctly using an HDHR connected to OTA.

Server and Placeshifter are running on Kubuntu 16.10, although it does not seem critical (I have also tried various combinations of the server on Ubuntu Server 16.04 LTS and the SageTV 9 Windows client with no change in results).  The only place where I can get a completely successful channel scan is using the Windows server with the Windows client.  I have migrated to Server and Placeshifter on Kubuntu 16.10 on another machine so I can continue to upgrade my SageTV 9 system hardware & software.

HDHR is the original, older (white) model, apparently now known as the HDHR Discover (this is what it reported when I updated the firmware).  Firmware is the latest from Silicon Dust's website as of last weekend (7/8/17) (I updated from 2014 firmware with no effect on this problem).

The problem is upon completion of the channel scan I have several clearly bogus channels simply numbered sequentially, starting with "-", then 2, 3, 4, ... up to 22 but sometimes up to 23 or 24.  After these channels, the expected results are shown and they appear complete.  I can simply disable the channels and move on, but I suspect this is aggravating other issues in the docker version of the server (where I really want to be) that make channel scan results basically useless for me.

In the log I see several entries that resemble the following:
```
Tue 7/11 23:17:27.863 [AsyncChannelSet@17c02a1d] ---  Processing scan result for digital tuner physical channel number 44
Tue 7/11 23:17:27.863 [AsyncChannelSet@17c02a1d] -----  scan result: 

Tue 7/11 23:17:27.863 [AsyncChannelSet@17c02a1d] Repeat channel name: [
]; adding a number to the channel name: [
19]
```

So it appears certain channel names are not being passed or processed correctly from the HDHR.  Once again the Windows SageTV 9 server/client appear immune to this issue.  Likewise a channel scan using HDHomerun_config within Ubuntu provides as-expected results.

Attached is the log from SageTV server on Kubuntu 16.10 from this evening.  I don't see a corresponding placeshifter log?

[sagetv_0.txt](https://github.com/google/sagetv/files/1140897/sagetv_0.txt)

Other logs may also be found in the related thread in the SageTV forums:  https://forums.sagetv.com/forums/showthread.php?t=64720

**Comment by CraziFuzzy** [comment]
It appears that on each scan that finds a channel, it is thinking there is one more stream than there really is, but with no info for the stream, it is creating a blank channel (and adding the number).  This is where your phantom channels with just a number are coming from.

For whatever reason, the SCANINFO string is returning a string with a trailing semicolon, as well as a CR/LF.  I think the parsing can deal with the trailing semicolon, since the StringTokenizer it is using to break it up will ignore empty tokens - but the CR/LF is not 'empty'.

I honestly have no idea where the CR/LF is coming from on your system.  The string passes through so many native and non-native functions, I get blurry-eyed trying to follow it (native code greatly dislikes me).

**Comment by CraziFuzzy** [comment]
IF you could, can you also attach Native.log from a channel scan?  Might give a little more debug info.

**Comment by texneus** [comment]
Would be happy to this evening when I get home.  To avoid a delay, could you tell me where to find this?  Is in the server or placeshifter directory (or somewhere else)?

**Comment by CraziFuzzy** [comment]
Should be in the server folder.

I ran some scans on my Docker server, and find it is also returning some screwy SCANINFO results when accessing the HDHR directly (I usually use OpenDCT for all my HDHR tuners).  The CR/LF at the end as well as the extra characters in some of the channel names.  It actually appears to be the extra characters are being added to any channel with more than 6 characters in it's name, which implies some sort of data overrun screwing things up.  Shorter channel names are coming back correct.

**Comment by CraziFuzzy** [comment]
could also be something that might be fixed in newer hdhomerunlib (the api's from silicondust).  I've got to roll up a VM for testing and maybe I can start debugging this, since I've confirmed I can replicate the issue locally.  No idea on timeframe to find a fix, so in the meantime openDCT works well, as does manually adjusting the mappings after the scan.

**Comment by texneus** [comment]
I can't find a native.log :-(.  Do you still need one?  Is there a property to set to get one?

I think you might be on to something with the 6 characters, I didn't make that correlation but from a quick scan that is something that the errors seem to have in common.  It will take a bit more time than I have tonight but let me take some time with the Ubuntu and docker logs and see if both problems completely correlate with that observation.

**Comment by enternoescape** [comment]
I think an assumption was made. Create the file NATIVE_LOG.ENABLE in your SageTV folder and then you might need to restart SageTV. After that you should start to see native.log.

**Comment by CraziFuzzy** [comment]
well, in my quick check, the 7 character channels had nothing to do with the line breaks.  They occurred on every frequency that had any detected channels.  The length of the channel name only seemed to affect whether the noise was added after the channel.

**Comment by texneus** [comment]
Sorry for the delay, had to get V9 setup before the guide data in V7 ran out.  Here is the native log from a channel scan this evening...
[Native.log.txt](https://github.com/google/sagetv/files/1154422/Native.log.txt)

**Comment by CraziFuzzy** [comment]
Well, on first glance through the native log, it looks like the strange characters are not coming from the native parts of the code, as they appear to be generating the scaninfo string properly, as evident in the "ATSC Scan Info" lines.  They do, however, have the unnecessary (and problematic) CR/LF in the string.

**Comment by CraziFuzzy** [comment]
@Narflex All of the scan methods in channel.c seem to add a "/r/n" to the end of the string if channels are found.  I'm wondering what the point of that is, since it does seem to be throwing the scan parsing for a loop, adding extra 'nothing' channels to the list.  I'm actually not sure why this is only happening on Linux and not a windows server, since this code seems to be the same (unless there's something I'm not finding in the DShowCapture code that removes what channel.c adds).

Seems poor form to put the line break in a string.  I get it being needed when transmitting human readable data via something like the network encoder, but that (EncodingServer.java) actually adds an additional linebreak there as well (which ultimately gets removed by NetworkCaptureDevice.java since it gets results via Sage.readLineBytes().

**Comment by CraziFuzzy** [comment]
Okay.. so I did find why windows doesn't have this problem, and it is that the "\r\n" is being trimmed off at DShowCapture-2/ScanChannel.cpp:144, making me really think that the addition needs to be removed from channel.c.  I'll give it a shot once I've got a build environment up and running again, and test what I can, but I'm really not sure what else (if anything) might use this info string.  (Can't think of anything at this point, but figured I'd ask).

**Comment by CraziFuzzy** [comment]
There's a chance I might have found the problem with the strange characters on the 7 character channel names as well.
ATSC PSIP sends the 'short channel name' as 7*2 bytes.
Sage's ATSC PSIP parse stores this as 9x2 bytes.
It copies from the stream into it's 9x2 byte array, so the name is in bytes 0-13 (actually overflowing a 4-bit seperator and the channel numbers into bytes 14-17).
It then attempts to null terminate the string with 'vct.name[sizeof(vct.name)-2] = 0x0;'.
'sizeof(vct.name)-2' is actually 16, however, so it's writing a 1-byte null into byte 16, without touching 17, while it should actually be terminating at byte 14 (sizeof(vct.name)-4).
It then processes this char array though TransJWideString, which looks for a 16-bit null terminator to properly format the string to pass back to java... which it never finds, resulting in the gibberish.  I think if we force in the terminators as
'vct.name[sizeof(vct.name)-4] =0x0; vct.name[sizeof(vct.name)-3] =0x0;' it should fix the strange character issues.  Of course, that said, I'm not sure why we are pulling 9*2 bytes for a fixed 7*2 channel name to begin with...

**Comment by CraziFuzzy** [comment]
OR... perhaps it's best to just prefill the char array with nulls and memcpy in JUST the 14 bytes the stream contains, like so:

`memset( vct.name, '\0', sizeof(vct.name) ); memcpy( vct.name, p, 7*2 );`

**Comment by Narflex** [comment]
I didnt write that code so I'm not sure how it's supposed to work, but if
initializing memory fixes it, that seems like a very safe change to make.

Jeff Kardatzke

**Comment by texneus** [comment]
I can confirm the changes correct the issue.  I will close the issue.  Thanks for the quick response, even if it took me a while to verify the fix on my system.
