### ISSUE TITLE
9.0.13+ wiz.bin not documented as incompatible with lower versions 

### ISSUE THREAD

**Issue by JREkiwi** [google/sagetv#346]
While trying to find a version that doesn't crash regularly, discovered that 9.0.13+ wiz.bin is not compatible with 9.0.12 and couldn't find anything documenting the fact.  9.0.12 is the last version I'm sure was working without crashing regularly, but I've had to settle on 9.0.13 rather than go back to an old wiz.bin.

**Comment by CraziFuzzy** [comment]
I'm not sure what an issue for an old version is going to accomplish.  Current version being worked on is 9.1.6.  Also, wiz.bin has never been backward compatible.

**Comment by JREkiwi** [comment]
Not really interested in getting into a argument about this.  The release notes historically have ALWAYS stated when wiz.bin was not compatible with earlier versions. See 7.0.17 release notes for example.  I have to go back to 9.0 as any of the 9.1 versions have frequent crashes with Out of Memory errors and unable to create native thread errors.

**Comment by enternoescape** [comment]
I agree that this kind of thing should be in the release notes because we have some users that will find this information helpful and commits don't really make it obvious when database changes have happened unless you understand the changes themselves. That being said, it never occurred to me that it was release note-worthy because most users just stay current. I remain curious why you continue to have OOM issues.
