### ISSUE TITLE
Pattern used for creating Singletons (e.g. Wizard, Seeker, etc...) is not thread safe

### ISSUE THREAD

**Issue by TuscanRaider** [google/sagetv#4]
The double null check for Singleton creation is not thread safe and expensive due to the synchronized lock.  (https://en.wikipedia.org/wiki/Double-checked_locking).

**Comment by Narflex** [comment]
Originally the synchronized check was never even in there because these singletons are all created on the main thread. We added this later for clarity so that other code changes didn't possibly break that (although I don't believe any such changes exist still).  It appears like technically it could be more correct...so feel free to submit a change fixing that. :)

**Comment by TuscanRaider** [comment]
Pull Request created!

**Comment by TuscanRaider** [comment]
Code merged
