### ISSUE TITLE
mvp.bin missing (purposeful?)

### ISSUE THREAD

**Issue by stuckj** [google/sagetv#66]
I discovered that mvp.bin doesn't appear to be in the repo so doesn't get included in the pre-packaged deb files created when you build from source. This prevents connections to a Linux sage server from a media MVP client (yes, I still use one even though it's ancient :-P). Is this purposeful (licensing issues maybe?). I noticed while setting up a linux box to replace my windows install of Sage (I've wanted to get rid of my only windows box for years :)). Using mvp.bin from the windows install works great, but thought it would be good to include in the source if not against any licensing restrictions.

**Comment by Narflex** [comment]
We did not include the mvp.bin file because the specific licensing around that file wasn't very straightforward. I don't recall exactly all the components in it; and to distribute open source code from Google...every single thing in there needs to have proper licensing attributed to it. Which is of course a very good policy to have. :)  There's nothing wrong with redistributing it...as we did for years...I just didn't want to take a huge amount of time to figure out exactly everything that was in there and what all the corresponding licenses were. You can still download that file from http://download.sagetv.com/mvp.bin if you are using a MediaMVP.

**Comment by stuckj** [comment]
Awesome, good to know there's a simple download link on sagetv.com. Also, kudos for making it relatively painless to transition from windows to linux...after copying wiz.bin and following the old post on fixing filename references in wiz.bin it's been a pretty easy transition. Glad I don't have to lose years (10?...don't even remember) of viewing history and recordings to dump Windows. :)
