### ISSUE TITLE
MCE remote button not working

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#90]
When I press the "Recorded TV", "Guide", "Live TV" and "i" buttons on the MCE remote, nothing happens. These buttons used to work, but now they do not work. When I press one of those buttons, the red light on the IR receiver blinks. The problem is not the MCE remote.

**Comment by Narflex** [comment]
What's changed from when they worked until now?

Jeff Kardatzke

**Comment by 49studebaker** [comment]
A few days ago, the "Play", "RWD", and "FWD" buttons also stopped working. Today, I did a backup of the Sage.properties and the Wiz.bin files. I uninstalled SageTV and then deleted its Program Files directory. I reinstalled SageTV and the "Play", "RWD", and "FWD" buttons are now working, but the  "Recorded TV", "Guide", "Live TV" and "i" buttons still do not work.

**Comment by 49studebaker** [comment]
I formatted and reinstalled Windows 10. I installed SageTV 9.0.3.214_beta0.002 and then moved Sage.Jar 9.0.4.232 to the SageTV directory. I also moved the new STV to the SageTV STV directory.  The "Recorded TV", "Guide", "Live TV" and "i" buttons still do not work. I do not think I had this problem with SageTV v7.

**Comment by Narflex** [comment]
I know I didn't touch any of the code relating to handling the MCE remote
from V7 to V9...but maybe it's being built in a way that's causing a
problem...or maybe this is just a Windows 10 compatibility issue. It'd be
very useful to know whether or not this works on SageTV 7 on Windows 10 or
not.

On Thu, Mar 24, 2016 at 10:12 PM, 49studebaker <notifications@github.com>
wrote:

> I formatted and reinstalled Windows 10. I installed SageTV
> 9.0.3.214_beta0.002 and then moved Sage.Jar 9.0.4.232 to the SageTV
> directory. I also moved the new STV to the SageTV STV directory. The
> "Recorded TV", "Guide", "Live TV" and "i" buttons still do not work. I do
> not think I had this problem with SageTV v7.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/90#issuecomment-201138963>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by Cyberdyne800** [comment]
I just upgraded my Sage server and clients to V9 (9.0.4.232) and now I am having the same problem that @49studebaker has described. Note that I am running Windows 10 64-bit and using an MCE remote. I had tried rolling back to previous releases of the V9 Sage.jar, but that had no affect on the problem.  As @Narflex suggested, I rolled both the server and client back to v7 to see if the problem was due to Windows 10 or due to Sage V9. It turns out that just moving Sage back to V7 returned the remote buttons to their correct behavior. And after returning to V9 the remote is not working correctly again.

**Comment by Narflex** [comment]
[WinDLLs.zip](https://github.com/google/sagetv/files/307589/WinDLLs.zip)

Can you try replacing the potential offending files from V9 with the files from V7? I've attached the 4 files that I'm suspect of (these are the V7 builds). If that does fix it, then try to narrow it down to which ones are actually needed, since I do not think it will be all of them and probably just one or two that are the problem.

**Comment by Cyberdyne800** [comment]
@Narflex thanks for posting the DLLs. After reading your post I realized that the problem was likely due to the fact that I was already using the version 7 DLL's. I did not realize that an installer was available and I had used the instructions from [here](http://forums.sagetv.com/forums/showthread.php?p=578056&postcount=4) to upgrade my original installation. After using the installer from github the problem disappeared. There is one annoying thing about the installer, SageTVClient.exe requires elevation to an admin to be run. Does anyone know if elevation is really necessary? I have been using Sage client for years with UAC enabled without problem.

**Comment by Cyberdyne800** [comment]
I withdraw my previous comment about UAC elevation and the SageTVClient. It seems the latest installer has fixed this issue.

**Comment by CraziFuzzy** [comment]
So just to clarify, using the full set of v9 files shipped with the latest installer, the MCE remote is working as expected, as well as the UAC issue?  If that's the case, can you close this issue?

**Comment by 49studebaker** [comment]
I replaced the SageTV 9 dlls with the dlls that you provided, and the MCE remote buttons still do not work.
